{"body": {"log": "because I can\nTraceback (most recent call last):\n  File \"\", line 143, in handle_step\n    output = self.handle_action_start(input_message['body'], logger, is_test, is_debug)\n  File \"\", line 205, in handle_action_start\n    output = func(params)\n  File \"\", line 16, in run\n    raise Exception('because I can')\nException: because I can\n", "status": "error", "meta": {}, "error": "because I can"}, "version": "v1", "type": "action_event"}